config/routes.rb
Rails.application.routes.draw do
  get 'invite/index'
  get 'notifications/index'
  get 'growth_records/index'
  #マイページ(一般ユーザー用)
  #get 'cake_types/edit'
  #get 'cake_types/update'
  devise_for :users, controllers: {
  registrations: 'users/registrations'
}
  root 'homes#top'
  get 'homes/top', to: 'homes#top'
  get 'about' => 'homes#about'

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  authenticate :user do
    get '/mypage', to: 'mypage#show', as: 'mypage'
    patch '/mypage', to: 'mypage#update'
  end

  get 'invite', to: 'invite#index'

  resources :users, only: [:show, :index, :edit, :update, :destroy] do
    member do
      get :following
      get :followers
      patch :withdraw
    end
  end

  resources :posts do
    collection do
      get :search
    end
    resources :comments, only: [:create, :destroy]
    resource :like, only: [:create, :destroy]
  end
  resources :likes, only: [:index]
  resources :relationships, only: [:create, :destroy]
  resources :exercise_logs, only: [:index, :new, :create]
  resources :growth_logs, only: [ :create]
  get '/growth', to: 'growth#show', as: :growth
  resources :growth,only: :show
  resource :cake_type, only:[:edit, :update]
  resource :mypage, only:[:show, :edit, :update]do
    delete :withdraw, to:"users#withdraw"
  end
  resources :growth_records, only:[:index, :create]
  resources :notifications, only: [:index, :show]

  #====管理者用==========
    namespace :admin do
    resources :users, only: [:index, :show, :destroy] do
      member do
        patch :withdraw
        patch :ban
        patch :unban
      end
    end 
    resources :comments, only: [:destroy]
  end
end

app/controllers/cake_types_controller.rb
class CakeTypesController < ApplicationController
  before_action :authenticate_user!

  def edit
    @user = current_user
  end

  def update
    if current_user.update(cake_type_params)
      redirect_to mypage_path, notice: "ケーキタイプを変更しました！🍰"
    else
      render :edit
    end
  end

  private

  def cake_type_params
    params.require(:user).permit(:cake_type)
  end
end

app/helpers/cake_types_helper.rb
module CakeTypesHelper
end

app/views/cake_types/edit.html.erb
<div class="cake-edit-wrapper">
  <h2>ケーキタイプを変更する</h2>
  <p>現在のケーキタイプ：<strong><%= cake_type_name(current_user.cake_type) %></strong></p>

  <%= form_with model: current_user, url: cake_type_path, method: :patch, local: true do |f| %>
    <%= f.radio_button :cake_type, :tart %> タルト<br>
    <%= f.radio_button :cake_type, :cake %> ショートケーキ<br>

    <%= f.submit "更新する", class: "btn mt-3" %>
  <% end %>

  <div class="back-btn mt-4">
    <%= link_to "戻る", mypage_path, class: "btn" %>
  </div>
  
</div>

app/views/cake_types/show.html.erb
<div class="exercise-wrapper text-center">
  <h2><%= @user.is_deleted? ? "退会済みユーザー" : @user.name %> さんのページ</h2>
  <p>メールアドレス：<%= @user.email %></p>

  <div class="cake-select">
    <h3>ケーキタイプ設定</h3>

    <% if current_user.cake_type.blank? %>
      <%= form_with model: current_user, url: mypage_path, method: :patch, local: true do |f| %>
        <div>
          <%= f.radio_button :cake_type, :tarte %>
          <%= f.label :cake_type_tarte, "タルト" %>
        </div>

        <div>
          <%= f.radio_button :cake_type, :shortcake %>
          <%= f.label :cake_type_shortcake, "ショートケーキ" %>
        </div>

        <%= f.submit "決定する", class: "btn mt-3" %>
      <% end %>

    <% else %>
      <p>あなたのケーキタイプ：<strong><%= current_user.cake_type %></strong></p>
      <%= link_to "変更する", mypage_path, method: :patch, class: "btn mt-3" %>
    <% end %>
  </div>

  <p class="mt-4">現在の成長ポイント：<%= @growth_point %>pt</p>

  <!-- 🍰ここは if の外側！どんな状態でも表示 -->
  <div class="mypage-edit-link">
    <%= link_to "マイページ情報を編集する", edit_mypage_path, class: "btn" %>
    <%= link_to "筋トレの記録を見る", exercise_logs_path, class: "btn btn-outline mt-3" %>
  </div>
</div>

app/views/cake_types/update.html.erb
<h1>CakeTypes#update</h1>
<p>Find me in app/views/cake_types/update.html.erb</p>